public class ListDemo {
    public static void candidateList(){
         List<string> listC = new list<string>();
         system.debug('before : ' + listC);
 
         //add values or elements or items in list
         listC.add('Marc');
         listC.add('Steve');
         listC.add('Kunal');
         listC.add('Marc');
         listC.add('Marc');
         system.debug('after : ' + listC);
    }
 
    public static void randomIntList(){
         list<integer> l1 = new list<integer>();
    }
 }