public class MathPractice {
    public void practiceOne( decimal a, decimal b) {
         system.debug('Dikdortgenin cevre uzunlugu ' + 2*(a+b));
             
    }

    public decimal practiceTwo( decimal a, decimal b) {
        return 2*(a+b);
       
     }



     
   public void practiceThree( ) {
   system.debug('Dikdortgenin cevre uzunlugu: ' );
  
   }

   public void practiceThree( decimal a) {
    practiceThree();
   
    }
}